### PR TITLE
molecule lint: most things fixed

### PR DESCRIPTION
**Pull request by stefangweichinger**
forked and introduced testing via molecule.
did some formatting changes to make "molecule lint" happy.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
sorry for including changes in meta/main.yml: did that locally for other reasons.

**Comment by colin-nolan** [comment]
Hi @stefangweichinger, thanks for the PR. I didn't know there was a linter for Ansible - I'll have to look into using it! Did you automate this testing with Molecule or did you just it manually? If the former, it would be good to whatever you're using to run the tests in this PR.

Aside from the unintentional changes to the meta, the linter has been over active here: 
https://github.com/mikolak-net/ansible-raspi-config/pull/18/files#diff-14d6db9d147ba6524c7768fb6ace1f5dL6. Are you able to correct these issues (you could rebase the meta change out, for example)? If you need any help, let me know.

**Comment by stefangweichinger** [comment]
@colin-nolan  molecule is usable via travis here, I might file another PR for that separately soon.
Forked this repo as I need some of the tasks in a project where I will remove some of the dependencies etc

The linter was OK here, but you will see yourself as soon as you use it ;-)
I'll try to remove that one meta change, yes.

**Comment by colin-nolan** [comment]
LGTM, thanks again

**Pull request merged**
